FART -r "..\public\*.html" "https://codepen.io/Kyleufree/full/JxeXZa" "index.html"
FART -r "..\public\*.html" "https://codepen.io/DonkeyKong246/full/vbrVyL" "edit.html"
FART -r "..\public\*.html" "https://codepen.io/DonkeyKong246/full/pYyzqB" "database.html"
FART -r "..\public\*.html" "https://codepen.io/DonkeyKong246/pen/JzeLBN" "outOfSchool.html"
FART -r "..\public\*.html" "<!-- main.css -->" "<link> <!-- link to CSS -->"
FART -r "..\public\*.html" "<!-- edit.css -->" "<link> <!-- link to CSS -->"
FART -r "..\public\*.html" "https://discourse-meta.s3-us-west-1.amazonaws.com/original/3X/2/2/229d84cddc571e97fe87aac0c5380e9c23c9e6b1.png" "images/pencil.png"
FART -r "..\public\*.html" "https://static.thenounproject.com/png/9658-200.png" "images/database.png"
FART -r "..\public\*.html" "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Love_Heart_SVG.svg/645px-Love_Heart_SVG.svg.png" "images/heart.png"
cmd /k